version: "3"

services:
  c1:
    build:
      context: .
      dockerfile: dockerfile-c1

  c2:
    build:
      context: .
      dockerfile: dockerfile-c2

  c3:
    build:
      context: .
      dockerfile: dockerfile-c3

  c4s1:
    build:
      context: .
      dockerfile: dockerfile-s1
    ports:
      - "2204:22"
    cap_add:
      - NET_RAW
      - NET_ADMIN
